module models {
    export class CountryRegionMap {
        public static map: any = {
            "South Asia": {
                "AFG": "Afghanistan",
                "BGD": "Bangladesh",
                "BTN": "Bhutan",
                "IND": "India",
                "PAK": "Pakistan"
            },
            "Europe & Central Asia": {
                "ALB": "Albania",
                "ARM": "Armenia",
                "AZE": "Azerbaijan",
                "BLR": "Belarus",
                "BIH": "Bosnia and Herzegovina",
                "BGR": "Bulgaria",
                "GEO": "Georgia",
                "HUN": "Hungary",
                "KAZ": "Kazakhstan",
                "KSV": "Kosovo",
                "KGZ": "Kyrgyz Republic",
                "MKD": "Macedonia, FYR",
                "MDA": "Moldova",
                "ROM": "Romania",
                "SRB": "Serbia",
                "TJK": "Tajikistan",
                "TUR": "Turkey",
                "UKR": "Ukraine",
                "UZB": "Uzbekistan"
            },
            "Middle East & North Africa": {
                "DZA": "Algeria",
                "EGY": "Egypt, Arab Rep.",
                "IRN": "Iran, Islamic Rep.",
                "JOR": "Jordan",
                "LBN": "Lebanon",
                "TUN": "Tunisia",
                "WBG": "West Bank and Gaza",
                "YEM": "Yemen, Rep."
            },
            "East Asia & Pacific": {
                "ASM": "American Samoa",
                "KHM": "Cambodia",
                "CHN": "China",
                "FJI": "Fiji",
                "IDN": "Indonesia",
                "LAO": "Lao PDR",
                "MYS": "Malaysia",
                "MNG": "Mongolia",
                "MMR": "Myanmar",
                "PNG": "Papua New Guinea",
                "PHL": "Philippines",
                "THA": "Thailand",
                "TMP": "Timor-Leste",
                "VNM": "Vietnam"
            },
            "Sub-Saharan Africa": {
                "AGO": "Angola",
                "BWA": "Botswana",
                "BFA": "Burkina Faso",
                "BDI": "Burundi",
                "CMR": "Cameroon",
                "GAB": "Gabon",
                "KEN": "Kenya",
                "LSO": "Lesotho",
                "LBR": "Liberia",
                "MDG": "Madagascar",
                "MOZ": "Mozambique",
                "NAM": "Namibia",
                "NER": "Niger",
                "RWA": "Rwanda",
                "SEN": "Senegal",
                "ZAF": "South Africa",
                "SSD": "South Sudan",
                "TGO": "Togo"
            },
            "Latin America & Caribbean": {
                "ARG": "Argentina",
                "BLZ": "Belize",
                "BOL": "Bolivia",
                "BRA": "Brazil",
                "COL": "Colombia",
                "CRI": "Costa Rica",
                "DOM": "Dominican Republic",
                "ECU": "Ecuador",
                "SLV": "El Salvador",
                "GTM": "Guatemala",
                "GUY": "Guyana",
                "HND": "Honduras",
                "JAM": "Jamaica",
                "MEX": "Mexico",
                "PAN": "Panama",
                "PRY": "Paraguay",
                "PER": "Peru",
                "SUR": "Suriname",
                "VEN": "Venezuela, RB"
            },
            "High income: OECD": {
                "AUS": "Australia",
                "AUT": "Austria",
                "BEL": "Belgium",
                "CAN": "Canada",
                "CHL": "Chile",
                "DNK": "Denmark",
                "EST": "Estonia",
                "FIN": "Finland",
                "FRA": "France",
                "DEU": "Germany",
                "GRC": "Greece",
                "ISL": "Iceland",
                "IRL": "Ireland",
                "ISR": "Israel",
                "ITA": "Italy",
                "JPN": "Japan",
                "KOR": "Korea, Rep.",
                "LUX": "Luxembourg",
                "NLD": "Netherlands",
                "NZL": "New Zealand",
                "NOR": "Norway",
                "POL": "Poland",
                "PRT": "Portugal",
                "SVK": "Slovak Republic",
                "SVN": "Slovenia",
                "ESP": "Spain",
                "SWE": "Sweden",
                "CHE": "Switzerland",
                "GBR": "United Kingdom",
                "USA": "United States"
            },
            "High income: non-OECD": {
                "BHR": "Bahrain",
                "BMU": "Bermuda",
                "BRN": "Brunei Darussalam",
                "HRV": "Croatia",
                "CYP": "Cyprus",
                "CZE": "Czech Republic",
                "GUM": "Guam",
                "HKG": "Hong Kong SAR, China",
                "LVA": "Latvia",
                "LIE": "Liechtenstein",
                "LTU": "Lithuania",
                "MLT": "Malta",
                "MNP": "Northern Mariana Islands",
                "OMN": "Oman",
                "RUS": "Russian Federation",
                "SAU": "Saudi Arabia",
                "SGP": "Singapore",
                "TWN": "Taiwan, China",
                "TTO": "Trinidad and Tobago",
                "URY": "Uruguay",
                "VIR": "Virgin Islands (U.S.)"
            }
        };
    }
}